### ISSUE TITLE
Reimplement (with futures and caching)

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/git-dit-wui#3]
We should reimplement everything with Futures and a Cache for aggregated data internally.

The current implementation is our first "playing" with the gotham framework. Now we should do it properly: Each handler should return a future. The cache implementation should be based on the principle "read from memory or, if not present, read from repository" and return futures as well.

This way we automatically get a multithreaded web interface. Right now it is single-threaded because our handlers are blocking.

@TheNeikos any experience with caching and how to do it properly? I know you use Rocket, but maybe some things are similar (design-wise)?

**Comment by TheNeikos** [comment]
It depends on what you want to cache, and when to bust it.

**Comment by matthiasbeyer** [comment]
After shutting down my machine yesterday I came to the conclusion that I need only a few things to cache:

- [ ] List of issues with their state (open/close, for optimization some metadata maybe)
- [ ] General statistics for the frontpage (number of issues, authors, number of messages)

That is rather simple, not the complex stuff I wanted to do with caching all the things.
But finding new issues is complex(ish) then.

Either way, reimplementing with futures is a nice idea.

**Comment by TheNeikos** [comment]
The question is mainly:

If you cache stuff it is because recomputing is costly.
When do you __do__ the computing then? On first access? In advance? Periodically in the background?

I imagine git-dit to be used in a semi-realtime fashion, after all its meant for discussion. Is a 5 second delay acceptable? 10? 60? 500? These all change the strategy you want to use and what you want to optimize for.

**Comment by matthiasbeyer** [comment]
I need to recompute at startup, of course. After that, I have no strategy yet, but as computation takes a lot of time, I guess a configurable delay would be nice. For example: Small repo: 10 secs. imag: 10 minutes.
